export const skills = [
    {
        id: 1,
        name: "React",
        level: "Advanced",
        icon: "⚛️",
        color: "neon-pink",
    },
    {
        id: 2,
        name: "JavaScript",
        level: "Advanced",
        icon: "📜",
        color: "neon-cyan",
    },
    {
        id: 3,
        name: "Tailwind CSS",
        level: "Intermediate",
        icon: "🎨",
        color: "neon-purple",
    },
    {
        id: 4,
        name: "Node.js",
        level: "Intermediate",
        icon: "🟢",
        color: "neon-green",
    },
    {
        id: 5,
        name: "Python",
        level: "Intermediate",
        icon: "🐍",
        color: "neon-cyan",
    },
    {
        id: 6,
        name: "Django",
        level: "Intermediate",
        icon: "🌐",
        color: "neon-purple",
    },
    {
        id: 7,
        name: "Flutter",
        level: "Intermediate",
        icon: "📱",
        color: "neon-pink",
    },
    {
        id: 8,
        name: "Salesforce",
        level: "Fellowship",
        icon: "☁️",
        color: "neon-cyan",
    },
    {
        id: 9,
        name: "AI / ML",
        level: "Enthusiast",
        icon: "🤖",
        color: "neon-pink",
    },
    {
        id: 10,
        name: "Git & GitHub",
        level: "Intermediate",
        icon: "🐙",
        color: "neon-purple",
    },
    {
        id: 11,
        name: "AWS Basics",
        level: "Learning",
        icon: "☁️",
        color: "neon-cyan",
    },
    {
        id: 12,
        name: "DevOps Basics",
        level: "Learning",
        icon: "🔧",
        color: "neon-green",
    },
];
